#!/bin/bash

# The bash script is used to find the missing jobs for the photon library generation. 
# Generated by Jiaoyang Li @ July 6 , 2022
type=xenon
# batch_number=6
output_dir=/pnfs/dune/scratch/users/jiaoyang/${type}/build_optical_${type}_0704_*/v09_49_00d00/gen

temp_list_file=List_of_Grid_files_${type}
temp_list_file2=List_of_Grid_files_missing_${type}
final_arrary_file=List_of_Grid_files_missing_array_${type}
# saving the number of each successful jobs. 
printf '%s\n' $output_dir/*/*.root | xargs -n 1 basename | cut -d'_' -f 1 > $temp_list_file
#ls -d $output_dir/*/*.root | xargs -n 1 basename | cut -d'_' -f 1 > $temp_list_file 

range_low=0 # `echo "$(head -n 1 $temp_list_file)"` # This corresponds to the region for number of jobs you submitted each subsection. 
range_high=`echo "($range_low +27115) " | bc`
comm -13  <(sort $temp_list_file) <(sort <(seq $range_low $range_high)) > $temp_list_file2 # Find the missing jobs.

# put them into array. 
readarray -t missing_arrary < $temp_list_file2 
echo ${missing_arrary[*]} > $final_arrary_file 

# Finishing, and printing out to debug.
echo "From subsection: $range_low to $range_high:"
echo "We have ${#missing_arrary[@]} missing files for this session."

rm -f $temp_list_file $temp_list_file2
